version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python server.py
    ports:
    - "8080:8080"
    expose:
      - "8080"
    volumes:
    - .:/app
